acseo_typesense:
  # Typesense host settings
  typesense:
    url: '%env(resolve:TYPESENSE_URL)%'
    key: '%env(resolve:TYPESENSE_KEY)%'
  # Collection settings
  collections:
    customers: # Typesense collection name
      entity: 'App\Entity\Customer'              # Doctrine Entity class
      fields:
        id: # Entity attribute name
          name: id                # Typesense attribute name
          type: primary
        sortable_id:
          entity_attribute: id
          name: sortable_id
          type: int32  # Attribute type
        name:
          name: name
          type: string
        city:
          name: city
          type: string                  # Object conversion with __toString()
        zipcode:
          name: zipcode
          type: string                  # Object conversion with __toString()
        address:
          name: address
          type: string
        customerContact.name:
          name: customer_contact_name          # equivalent of $book->getAuthor()->getCountry()
          type: string
        customerContact.description:
          name: customer_contact_description          # equivalent of $book->getAuthor()->getCountry()
          type: string            # Convert ArrayCollection to array of strings
      default_sorting_field: sortable_id
