# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    totp:
        enabled: false                  # If TOTP authentication should be enabled, default false
        server_name: Server Name       # Server name used in QR code
        issuer: Issuer Name            # Issuer name used in QR code
        leeway: 0                      # Acceptable time drift in seconds, must be less or equal than the TOTP period
        template: security/2fa_form.html.twig   # Temp
    google:
        enabled: false                  # If Google Authenticator should be enabled, default false
        server_name: Server Name       # Server name used in QR code
        issuer: Issuer Name            # Issuer name used in QR code
        digits: 6                      # Number of digits in authentication code
        leeway: 0
        template: security/2fa_form.html.twig   # Temp
    email:
        enabled: true                     # If email authentication should be enabled, default false
#        mailer: acme.custom_mailer_service  # Use alternative service to send the authentication code
#        code_generator: acme.custom_code_generator_service  # Use alternative service to generate authentication code
#        sender_email: me@example.com   # Sender email address
#        sender_name: John Doe          # Sender name
#        digits: 4                      # Number of digits in authentication code
#        template: security/2fa_form.html.twig   # Template used to render the authentication form
