version: '3'

services:

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
###< symfony/mailer ###

#  typesense:
#    image: typesense/typesense:0.23.1
#    environment:
#      TYPESENSE_DATA_DIR: /data
#      TYPESENSE_API_KEY: apikey
#    volumes:
#      - /tmp/typesense-server-data:/data
#    ports:
#      - 8108:8108
#    restart: "no"
