version: '3'

services:

  ###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
  ###< symfony/mailer ###

  gotenberg:
    container_name: gotenberg_qizuna
    image: gotenberg/gotenberg:7
    ports:
      - "3000:3000"

  meilisearch:
    container_name: meilisearch_qizuna
    image: getmeili/meilisearch
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: mymeilikey
      MEILI_CONFIG_FILE_PATH: /config/config.toml
    volumes:
      - ./var/meili_data:/meili_data
      - ./config/meilisearch:/config
