version: '3'

services:

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
###< symfony/mailer ###

  meilisearch:
    image: getmeili/meilisearch
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY : qizuna
      MEILI_CONFIG_FILE_PATH: /config/config.toml
    volumes:
      - ./var/meili_data:/meili_data
      - ./config/meilisearch:/config
